### ISSUE TITLE
[BUG]:  Addon not functioning anymore.

### ISSUE THREAD

**Issue by Gasteren** [HizurosWoWAddOns/GuildApplicantTracker#1]
### WoW client

WoW Retail

### What happened?

The addon does no longer work.
it does not respond to any of the command and no pop ups appear.

### Lua Error Message?

```lua
None as far as ive seen
```

### Other addons?

Guild Roster Manager maybe?

**Comment by Gasteren** [comment]
Addon most likely abandoned

**Comment by hizuro** [comment]
Sorry. that i overlooked your ticket.

Today I've tested it with and without Guild Roster Manager and see no problems.

**Comment by Gasteren** [comment]
> Sorry. that i overlooked your ticket.
> 
> Today I've tested it with and without Guild Roster Manager and see no problems.

Thanks alot, i will go check it out and no worries, just did not want to clutter your tickets with my bs haha
